# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.8
  - 3.7
  - 3.6

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U poetry
  - pip install -U tox-travis
  - pip install -U coverage
  - pip install -U coveralls
  - pip install -U codecov
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

# Command to run tests, e.g. python setup.py test
script:
  - tox
  - coverage run --source asamplelib -m pytest
  - coverage report -m

after_script:
  - coveralls
  - codecov
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password

before-deploy:
  - poetry config http-basic.mypypi $MYPYPI_USER $MYPYPI_PASS
  - poetry config http-basic.testpypi $MYPYPI_USER $MYPYPI_PASS
  - poetry config repositories.testpypi https://test.pypi.org/legacy/
  - poetry build

deploy:
  skip_cleanup: true
  provider: script
  script: poetry publish -r testpypi
  on:
    tags: true
    repo: tomestro/asamplelib
    branch: master
    python: 3.8
